### ISSUE TITLE
UIO is Unnecessary

### ISSUE THREAD

**Issue by ElvishJerricco** [ocharles/interpreters#2]
In `Control.Effect.IO`, the `UIO` type is simply a wrapper around `IO`. It would be just as effective to simply deal with the `IO` type, rather than have anything to do with `UIO`. The whole module can be rewritten like this.

``` haskell
-- | Lift an 'IO' action and explictly throw an synchronous IO exceptions that
-- occur.
syncIO :: (Interprets (Either SomeException) m,EffIO m)
       => IO a -> m a
syncIO io = effIO (try io) >>= interpret -- TODO This is catching async

runExceptionalIO :: EffIO m => Eff (Either SomeException) m a -> m a
runExceptionalIO = Ex.try >=> either (effIO . throwIO) return

class Monad m => EffIO m where
  effIO :: IO a -> m a

instance EffIO IO where
  effIO = id

instance EffIO m => EffIO (Eff r m) where
  effIO = lift . effIO
```

Or honestly, maybe `EffIO` should be replaced with corresponding `MonadIO` instances in `Control.Effect`.

**Comment by mitchellwrosen** [comment]
Any thoughts on this @ocharles?

**Comment by ocharles** [comment]
This module was never really fully thought out. The rough idea is that `IO` describes `IO` actions *and* the possibility of synchronous exceptions being thrown. `UIO` describes *only* `IO` actions. As it stands, exporting the `UIO` constructor is unsafe, as it lets you circumvent the whole system. We do probably need to export the constructor, but it should be clearly marked as unsafe. There are probably a bunch of options we have here, but I'm not actively working on this project at the moment.
